

"""Tests for `om4mtools.core.utils`."""

from __future__ import annotations
from pathlib import Path


import numpy as np
import pytest

from om4mtools.core.utils import peaks

DATA_DIR = Path(__file__).resolve().parents[1] / "data"
PEAKS_CSV = DATA_DIR / "peaks_49x50.csv"

@pytest.fixture
def matlab_reference_peaks_49x50() -> np.ndarray:
    """Load the MATLAB reference surface for peaks(49, 50).

    Generated by `tests/data/peaks_49x50.m`, which samples the same
    analytic peaks formula directly on a 49 (rows, y) x 50 (cols, x)
    grid via ``meshgrid(linspace(-3, 3, 50), linspace(-3, 3, 49))`` and
    writes the result with `writematrix(z, 'peaks_49x50.csv')`. Run that
    script from MATLAB (with `tests/data/` as the working directory) to
    regenerate `tests/data/peaks_49x50.csv` if the reference ever needs
    updating.

    Run just this fixture's consumer:
        pytest tests/unit/test_utils.py::test_peaks_matches_matlab_ref -v
    """
    z = np.loadtxt(PEAKS_CSV, delimiter=",")
    return z


@pytest.mark.smoke
def test_peaks_shape_matches_n_rows_n_cols() -> None:
    """Output grids follow (n_rows, n_cols), not (n_cols, n_rows).

    Run:
        pytest tests/unit/test_utils.py::test_peaks_shape_matches_n_rows_n_cols -v
    """
    z = peaks(4, 7)

    assert z.shape == (4, 7)


@pytest.mark.smoke
def test_peaks_matches_matlab_ref(matlab_reference_peaks_49x50: np.ndarray) -> None:
    """peaks(49, 50) matches the MATLAB reference from `peaks_49x50.m`.

    Run:
        pytest tests/unit/test_utils.py::test_peaks_matches_matlab_ref -v
    """
    z = peaks(49, 50)
    assert z.shape == (49, 50)

    np.testing.assert_allclose(z, matlab_reference_peaks_49x50, rtol=1e-6, atol=1e-9)





    
